from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent
CLIENT_FTP_HOST = "127.0.0.1"
CLIENT_FTP_PORT = 2121
CLIENT_FTP_USERNAME = "testuser"
CLIENT_FTP_PASSWORD = "1234"
CLIENT_FTP_ROOT_PATH = "/RUIP"

SERVER_FTP_HOST = "127.0.0.1"
SERVER_FTP_PORT = 2121
SERVER_FTP_USERNAME = "testuser"
SERVER_FTP_PASSWORD = "1234"
SERVER_FTP_ROOT_PATH = "/RESULT"

LOCAL_FTP_HOME_DIR = PROJECT_DIR / "ftp_root"
LOCAL_CLIENT_SCAN_DIR = LOCAL_FTP_HOME_DIR / CLIENT_FTP_ROOT_PATH.lstrip("/")
LOCAL_SERVER_SCAN_DIR = LOCAL_FTP_HOME_DIR / SERVER_FTP_ROOT_PATH.lstrip("/")
LOCAL_WORK_DIR = PROJECT_DIR / "ftp_work"
LOCAL_DB_PATH = PROJECT_DIR / "pipeline.sqlite3"
FTP_PASSIVE_MODE = True
RUPI_SCALE_PERCENT = 50
