alter table prism_common.er_dose_error_parsed
    drop column if exists log_source,
    drop column if exists raw_contents,
    drop column if exists repair_yn,
    drop column if exists repair_result,
    drop column if exists parser_version,
    drop column if exists parsing_status,
    drop column if exists parsing_error,
    drop column if exists source_exposure_id,
    drop column if exists wafer_seq,
    drop column if exists shot_seq,
    drop column if exists field_seq,
    drop column if exists dose_error,
    drop column if exists dose_warn_level,
    drop column if exists de_warn_lvl,
    drop column if exists eset,
    drop column if exists freq,
    drop column if exists mb_enabled,
    drop column if exists function_name,
    drop column if exists result_type,
    add column if not exists er_date int4,
    add column if not exists er_index int4,
    add column if not exists er_line varchar(20),
    add column if not exists eq_name varchar(20),
    add column if not exists code varchar(20),
    add column if not exists code_occur_time timestamp(6),
    add column if not exists belong varchar(12),
    add column if not exists "type" varchar(8),
    add column if not exists title varchar,
    add column if not exists contents varchar,
    add column if not exists exposure_handle bigint,
    add column if not exists action_handle bigint,
    add column if not exists wafer_id integer,
    add column if not exists de_err numeric(12,7),
    add column if not exists n_slit integer;
