alter table prism_common.er_dose_error_root_cause
    drop column if exists source_log_source,
    drop column if exists source_belong,
    drop column if exists source_type,
    drop column if exists raw_description,
    drop column if exists scanner_exposure_handle,
    drop column if exists source_code,
    drop column if exists match_status,
    drop column if exists parser_version,
    add column if not exists er_type varchar(10),
    add column if not exists belong varchar(12),
    add column if not exists "type" varchar(8),
    add column if not exists title varchar,
    add column if not exists contents varchar,
    add column if not exists reason_code varchar(20),
    add column if not exists task varchar,
    add column if not exists compile_script varchar,
    add column if not exists source_file_name text,
    add column if not exists exposure_length numeric(12,7),
    add column if not exists duty_cycle numeric(12,7),
    add column if not exists min_dose_error numeric(12,7),
    add column if not exists max_dose_error numeric(12,7),
    add column if not exists on_drop_euv_energy numeric(12,7),
    add column if not exists on_drop_pp_energy numeric(12,7),
    add column if not exists on_drop_mp_energy numeric(12,7),
    add column if not exists on_drop_pp_dlgc1 numeric(12,7),
    add column if not exists on_drop_mp_dlgc1 numeric(12,7),
    add column if not exists bi_cell_y_3sigma numeric(12,7),
    add column if not exists fdsc_y_error numeric(12,7),
    add column if not exists fdsc_y_3sigma numeric(12,7),
    add column if not exists max_cross_interval numeric(12,7),
    add column if not exists xint_3sigma numeric(12,7),
    add column if not exists euv_3sigma numeric(12,7),
    add column if not exists pulses_euv_lt_0_6dt_tot integer,
    add column if not exists fed_pulses integer,
    add column if not exists l2dx_maxce numeric(12,7),
    add column if not exists l2dy_maxce numeric(12,7),
    add column if not exists sensitivity_at_l2dx_maxce numeric(12,7),
    add column if not exists sensitivity_at_l2dy_maxce numeric(12,7),
    add column if not exists dose_margin numeric(12,7),
    add column if not exists l2dx_qc_etdc_3sigma numeric(12,7),
    add column if not exists l2dx_qc_etdc_median numeric(12,7),
    add column if not exists l2dy_qc_etdc_3sigma numeric(12,7),
    add column if not exists l2dy_qc_etdc_median numeric(12,7),
    add column if not exists rbdy_peak_frequency_hf numeric(12,7),
    add column if not exists rbdy_peak_frequency_lf numeric(12,7),
    add column if not exists rbdy_peak_frequency_mf numeric(12,7),
    add column if not exists rbdy_peak_power_hf numeric(12,7),
    add column if not exists rbdy_qc_etdc_3sigma numeric(12,7),
    add column if not exists rbdy_total_power_lf numeric(12,7),
    add column if not exists rbdy_total_power_mf numeric(12,7),
    add column if not exists software_version text;
